[book]
title = "Atomic notes"
authors = ["Ruslan Yunisov"]
language = "en"
multilingual = false
src = "src"

[preprocessor.emojicodes]
renderer = ["html"]

[output.html]
site-url = "/atomic-notes/"
git-repository-url = "https://github.com/ryunisov/atomic-notes/tree/main/"

